baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'MCP Selenium Server'
theme = ''

# Basic configuration
[params]
  description = 'MCP Server for browser automation using Selenium WebDriver'

# Output formats
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# Build configuration
[build]
  noJS = false
  useResourceCache = true
